create table if not exists loan_variations(
variations_code bigint not null,
loan_id bigint null,
primary_account_num bigint null,
lending_account varchar(255) null,
lending_amount bigint null,
variations_text varchar(255) null,
is_read varchar(255) null,
remarks varchar(255) null,
description varchar(255) null,
loan_input_avail char null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint loan_variations_pk primary key(variations_code));